const strings = {
  ja: {
    // Welcome Page
    welcomeTitle: "音量ブースターへようこそ！",
    welcomeSubtitle: "インストールありがとうございます。基本的な使い方をご紹介します。",
    welcomeSection1Title: "1. メイン機能：音量ブースト",
    welcomeSection1Desc1: "ツールバーにある拡張機能のアイコンをクリックします。",
    welcomeSection1Desc2: "スライダーを動かして、音量を最大600%までブーストできます！",
    welcomeSection1Desc3: "設定はドメインごとに自動保存され、次回開いた時も適用されます。",
    welcomeSection2Title: "2. その他の便利機能（オプション）",
    welcomeSection2Intro: "この拡張機能には、他にも便利な機能がたくさんあります。拡張機能アイコンを右クリックして「オプション」から設定できます。",
    welcomeFeature1Title: "YouTube Live音量調整",
    welcomeFeature1Desc: "YouTube Liveを開いた時だけ、自動的に指定した音量に変更します。",
    welcomeFeature2Title: "YouTube自動音量",
    welcomeFeature2Desc: "YouTubeを開いた時、常に決まった音量で再生を開始します。",
    welcomeFeature3Title: "マウスホイールで音量調整",
    welcomeFeature3Desc: "YouTubeやTwitchの動画プレイヤー上でマウスホイールを回すと、直感的に音量を調整できます。",
    getStartedBtn: "使い始める（閉じる）",
    openOptionsBtn: "設定画面を見てみる",
    // General
    appName: "音量ブースター",
    manageSettings: "すべての設定を管理",
    // Popup
    currentTab: "現在のタブのみ",
    siteWide: "サイト全体",
    accountSpecific: (name) => `アカウント (${name})`,
    active: "適用中",
    reset: "設定を削除",
    resetDomain: "サイト全体の設定を削除",
    resetAccount: "アカウントの設定を削除",
    resetTemp: "現在のタブの設定をリセット",
    noSettingsToReset: "すべてデフォルト設定です",
    statusUnsupported: "このページでは使用できません。",
    // Options
    optionsTitle: "音量ブースター設定",
    accountSettings: "アカウント別設定",
    domainPlaceholder: "youtube.com",
    add: "追加",
    headerDomain: "ドメイン",
    headerAccount: "アカウント名",
    headerBoost: "ブースト率",
    headerAction: "操作",
    deleteAction: "削除",
    resetAction: "リセット",
    editAction: "編集",
    deleteConfirm: (domain) => `${domain} の設定を削除しますか？`,
    alertDomain: "ドメイン名を入力してください。",
    alertBoost: "ブースト率には0から600までの数値を入力してください。",
    resetSettings: "設定をリセット",
    resetConfirm: "設定をリセットしてもよろしいですか？この操作は元に戻せません。",
    resetDomains: "ドメインをすべてリセット",
    resetDomainsConfirm: "すべてのドメイン設定をリセットしますか？",
    resetAccounts: "YouTubeアカウント別設定をすべてリセット",
    resetAccountsConfirm: "すべてのYouTubeアカウント別設定をリセットしますか？",
    resetFeatures: "その他の機能をすべてリセット",
    resetFeaturesConfirm: "YouTubeライブ、自動音量、ホイール操作などの設定をすべてリセットしますか？",
    resetAllSettings: "すべての設定をリセット",
    resetAllConfirm: "テーマと言語以外のすべての設定をリセットしますか？",
    // Tooltips
    tooltipDomain: "このサイト全体の音量を設定します (保存されます)",
    tooltipAccount: "このアカウントの音量を設定します (保存されます)",
    tooltipTemp: "現在のタブの音量のみ一時的に変更します",
    // New Settings
    generalSettings: "一般設定",
    youtubeLiveSettings: "YouTube Live設定",
    enableYoutubeLiveLowering: "YouTubeライブで音量を変更する",
    targetVolume: "目標音量",
    // Auto Volume Settings
    youtubeAutoSettings: "YouTube自動音量設定",
    enableYoutubeAuto: "YouTubeを開いた時に音量を自動設定する",
    defaultVolume: "既定の音量",
    // Scroll Settings
    mouseWheelSettings: "マウスホイール音量設定",
    youtubeScrollSettings: "YouTube",
    twitchScrollSettings: "Twitch",
    enableYoutubeScroll: "YouTubeでホイール音量調整を有効にする",
    enableTwitchScroll: "Twitchでホイール音量調整を有効にする",
    scrollStep: "ホイール1目盛りの変化量 (%)"
  },
  en: {
    // Welcome Page
    welcomeTitle: "Welcome to Volume Booster!",
    welcomeSubtitle: "Thank you for installing. Here is a quick guide on how to use it.",
    welcomeSection1Title: "1. Main Feature: Volume Boost",
    welcomeSection1Desc1: "Click the extension icon in your browser toolbar.",
    welcomeSection1Desc2: "Use the slider to boost the volume up to 600%!",
    welcomeSection1Desc3: "Settings are automatically saved per domain and applied next time.",
    welcomeSection2Title: "2. Other Awesome Features (Options)",
    welcomeSection2Intro: "This extension has more useful features. Right-click the extension icon and select 'Options' to enable them.",
    welcomeFeature1Title: "YouTube Live Volume Control",
    welcomeFeature1Desc: "Automatically set a specific volume only when you open YouTube Live streams.",
    welcomeFeature2Title: "YouTube Auto Volume",
    welcomeFeature2Desc: "Always start videos at your preferred volume when you open YouTube.",
    welcomeFeature3Title: "Mouse Wheel Volume Control",
    welcomeFeature3Desc: "Intuitively adjust the volume by scrolling your mouse wheel on YouTube or Twitch players.",
    getStartedBtn: "Get Started (Close)",
    openOptionsBtn: "Go to Settings",
    // General
    appName: "Volume Booster",
    manageSettings: "Manage All Settings",
    // Popup
    currentTab: "Current Tab Only",
    siteWide: "Site-wide",
    accountSpecific: (name) => `Account (${name})`,
    active: "Active",
    reset: "Remove Setting",
    resetDomain: "Remove Site-wide Setting",
    resetAccount: "Remove Account Setting",
    resetTemp: "Reset Current Tab Setting",
    noSettingsToReset: "All settings are default",
    statusUnsupported: "Not available on this page.",
    // Tooltips
    tooltipDomain: "Set volume for this entire site (Saved)",
    tooltipAccount: "Set volume for this account (Saved)",
    tooltipTemp: "Temporarily change volume for current tab only",
    // Options
    optionsTitle: "Volume Booster Settings",
    accountSettings: "Account Settings",
    domainPlaceholder: "youtube.com",
    add: "Add",
    headerDomain: "Domain",
    headerAccount: "Account Name",
    headerBoost: "Boost %",
    headerAction: "Action",
    deleteAction: "Delete",
    resetAction: "Reset",
    editAction: "Edit",
    deleteConfirm: (domain) => `Are you sure you want to delete the setting for ${domain}?`,
    alertDomain: "Please enter a domain name.",
    alertBoost: "Please enter a boost value between 0 and 600.",
    resetSettings: "Reset Settings",
    resetConfirm: "Are you sure you want to reset settings? This cannot be undone.",
    resetDomains: "Reset all domains",
    resetDomainsConfirm: "Are you sure you want to reset all domain settings?",
    resetAccounts: "Reset all YouTube account settings",
    resetAccountsConfirm: "Are you sure you want to reset all YouTube account settings?",
    resetFeatures: "Reset all other features",
    resetFeaturesConfirm: "Are you sure you want to reset YouTube Live, Auto Volume, and Scroll settings?",
    resetAllSettings: "Reset all settings",
    resetAllConfirm: "Are you sure you want to reset all settings (excluding theme and language)?",
    // New Settings
    generalSettings: "General Settings",
    youtubeLiveSettings: "YouTube Live Settings",
    enableYoutubeLiveLowering: "Change volume on YouTube Live",
    targetVolume: "Target Volume",
    // Auto Volume Settings
    youtubeAutoSettings: "YouTube Auto Volume Settings",
    enableYoutubeAuto: "Automatically set volume when opening YouTube",
    defaultVolume: "Default Volume",
    // Scroll Settings
    mouseWheelSettings: "Mouse Wheel Volume Settings",
    youtubeScrollSettings: "YouTube",
    twitchScrollSettings: "Twitch",
    enableYoutubeScroll: "Adjust volume via mouse wheel on YouTube",
    enableTwitchScroll: "Adjust volume via mouse wheel on Twitch",
    scrollStep: "Volume change per step (%)"
  }
};
